### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by JakobMiksch** [pblottiere/QSA#3]
Thanks for the project. It looks really promising. I would like to try it, but I fail to install it. So far I did:

```sh
poetry install
```

I do not find a way to run `qsa qsa.yml`. Maybe I am missing a simple step here (since I am currently not that deep into Python)

Could you provide some hints how to get QSA running?

**Comment by pblottiere** [comment]
Hello @JakobMiksch,

First thanks for your interest! QSA is already used in production by https://www.promethee.earth, but you're the first "external" user :). 

I added an *Installation* chapter : https://github.com/pblottiere/QSA?tab=readme-ov-file#installation. Let me know what you think.

BTW, can I ask you if you're planning on using QGISServer paired with MapProxy or only with QGIS Server? Because MapProxy support should be optional, but it's not the case for now...

**Comment by JakobMiksch** [comment]
With your updated instructions I was able to start the tool on Ubuntu. Thanks for that 👍 

I am testing QSA for a setup where we do not use MapProxy (but maybe in future). Also our QGIS projects live in a PostGIS database, and not on the file system.

Do I understand correctly that QSA currently only supports QGIS projects in specific directory?

**Comment by pblottiere** [comment]
> With your updated instructions I was able to start the tool on Ubuntu. Thanks for that 👍

Nice. I also need to add a tutorial of some sort...

> I am testing QSA for a setup where we do not use MapProxy (but maybe in future).

Ok, I'm going to take a look for removing the mandatory usage of MapProxy asap.

> Also our QGIS projects live in a PostGIS database, and not on the file system.
> Do I understand correctly that QSA currently only supports QGIS projects in specific directory?

Yes indeed but using QGIS projects stored in PostGIS is also on my TODO list. I'll probably have some funds to work on this subject soon :crossed_fingers:. 

Could you create an issue (or several) describing your needs please? Then I'll be able to let you know when/if it's ready.

FYI, I'm also working on a QGIS Server plugin (`qsa-plugin`) and a command line tool (`qsa-cli`) for monitoring QGIS Server instances, so the repository content will probably change a lot in the coming weeks...

**Comment by JakobMiksch** [comment]
> Could you create an issue (or several) describing your needs please? Then I'll be able to let you know when/if it's ready.

I created these issues which roughly cover my use case : #4 #5 #6 #7 

> Yes indeed but using QGIS projects stored in PostGIS is also on my TODO list. I'll probably have some funds to work on this subject soon 🤞.

> FYI, I'm also working on a QGIS Server plugin (`qsa-plugin`) and a command line tool (`qsa-cli`) for monitoring QGIS Server instances, so the repository content will probably change a lot in the coming weeks...

These developments sound very interesting. I am ready to test any development, any maybe I can even try to contribute.

**Comment by pblottiere** [comment]
Hello @JakobMiksch,


>> With your updated instructions I was able to start the tool on Ubuntu. Thanks for that 👍

> Nice. I also need to add a tutorial of some sort...

FYI I added a proper documentation with a `Sandbox` chapter to discover the API and the cli: https://pblottiere.github.io/QSA/sandbox

>> Could you create an issue (or several) describing your needs please? Then I'll be able to let you know when/if it's ready.

> I created these issues which roughly cover my use case : https://github.com/pblottiere/QSA/issues/4 https://github.com/pblottiere/QSA/issues/5 https://github.com/pblottiere/QSA/issues/6 https://github.com/pblottiere/QSA/issues/7

Nice, thanks for your time :+1:.

>> FYI, I'm also working on a QGIS Server plugin (qsa-plugin) and a command line tool (qsa-cli) for monitoring QGIS Server instances, so the repository content will probably change a lot in the coming weeks...

> These developments sound very interesting. I am ready to test any development, and maybe I can even try to contribute.

A `qsa-plugin` QGIS Server plugin and a `qsa-cli` have been merged yesterday. The documentation is available on https://pblottiere.github.io/QSA/.

These components are still under development, but it's ready for testing.
