### ISSUE TITLE
Add layers of PostGIS

### ISSUE THREAD

**Issue by JakobMiksch** [pblottiere/QSA#7]
This more a question, because maybe this functionality already exists.

Is it possible to add a layer of a PostGIS database to a QGIS Project?

**Comment by JakobMiksch** [comment]
Hi @pblottiere , I have tried opening a QGIS project stored in Postgres and it works so far.
I would like to add layers stored in PostGIS as well, but without success so far.
Here my try:

```sh

curl "http://localhost:5000/api/projects/my_project/layers?schema=my_schema" \
  -X POST \
  -H 'Content-Type: application/json' \
  -d '{
    "crs": 4326,
    "datasource":"dbname='qsa' host=localhost port=5433 user='qsa' key='id' srid=4326 type=MultiPolygon checkPrimaryKeyUnicity='1' table=\"my_schema\".\"world\" (geom)",
    "name":"polygons",
    "type":"vector"
  }'
```

Response is:

```sh
{"error":"Invalid layer"}
```

Have you tried adding a layer from a PostGIS DB so far?

**Comment by pblottiere** [comment]
Hello @JakobMiksch,

> Have you tried adding a layer from a PostGIS DB so far?

No not yet (our data is mainly hosted on S3 buckets). I'm going to take a look ASAP.

**Comment by pblottiere** [comment]
The PR https://github.com/pblottiere/QSA/pull/22 adds PostGIS support for vector layers :tada:. I also updated the sandbox documentation chapter with a `line` geometry vector layer based on PostGIS:

``` console
$ curl "http://localhost:5000/api/projects/my_project/layers?schema=my_schema"   -X POST   -H 'Content-Type: application/json'   -d '{
    "crs": 4326,
    "datasource":"service=qsa table=\"public\".\"lines\" (geom)",
    "name":"lines",
    "type":"vector"
  }'
```
